#+TITLE: matplotlib的学习笔记
#+DATE: [2021-11-24 Wed 10:59]
* 这篇博客记录学习 matplotlib 的笔记
  最近心血来潮，想起来了 =python= ，重新了解一下，首先就把基础的画图进行了解一下。我学习 =matplotlib= 主要来自这个网站 [[https://matplotlib.org/][matplotlib.org]]。
  以后估计还会搞一手 =Django= 来做一手 web 开发，这是我一直想要学的东西。
  #+begin_export html
<!-- more -->
  #+end_export
** lifecycle
   对于我来说，我不是很喜欢 =MATLAB= 风格的画图方式，所以我一般都是采用面向对象的接口来进行画图操作
   #+begin_src python :results file
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
X = np.linspace(0, 4*np.pi, 200)
Y = np.tan(X)
fig, ax = plt.subplots()
ax.plot(X, Y)
ax.set_title("Lifecycle")
ax.set_xlabel("X Labels")
ax.set_ylabel("Y Labels")
plt.tight_layout()
plt.savefig("result.svg")
return("result.svg")
   #+end_src

   #+RESULTS:
   [[file:result.svg]]


   所以说有些操作还是比较有意思

   - =plt.style.available= 可以查看支持的主题，我的 emacs 用的是 =solarized-gruvbox-dark= ,所以 =Solarize_Light2= 适合我使用。<<style>>
   - =fig.canvas.get_supported_filetypes()= 查看支持保存的图片的格式。
** customize
   可以自己定义 matplotlib 显示图案的样式。
   =import matplotlib as mpl= ，接着就是使用 =mpl.rcParams[]= 一个接着一个定义，或者 =mpl.rc()= 一起定义
   #+begin_src python :results file
import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np
mpl.rcParams['lines.linewidth']=2
mpl.rcParams['lines.linestyle']='--'
data = np.random.randn(40)
# or
# mpl.rc('lines', linewidth=4, linestyle="-")
# plt.plot(data)
plt.plot(data)
plt.savefig("e.svg")
return("e.svg")
   #+end_src

   #+RESULTS:
   [[file:e.svg]]
   最主要的还是可以进行局部改变进行画图
   #+begin_src python
with mpl.rc_context({"lines.linewidth": 3, "lines.linestyle": "-"}):
    plt.plot(data)
# 搞个装饰器
@mpl.rc_context({'lines.linewidth': 3, 'lines.linestyle': '-'})
def plotting_function():
    plt.plot(data)

plotting_function()
   #+end_src
   上面的代码所获得的结果是一模一样的。
   你也是可以通过 [[style]] 进行更改，有意思的是可以进行混合的，比如
   #+begin_src python
plt.style.use["Solarize_Light2", "dark_background"]
   #+end_src

** 今天学习在 matplotlib 中进行部分 LaTeX 的渲染 [2021-11-26 Fri 15:33]
   首先需要明确的是， =python= 中会对一些字符识别为转义字符，所以你需要防止转义。
   例如 =plt.title(r"$\tan x > \beta$")= ，不加的话， =\tan= 就会被识别为 =\t= 制表符。
   =r$\frac{a}{b}$= ，emacs 的 org-mode 可以与 cdlatex hook。
   #+begin_src emacs-lisp
(add-hook 'org-mode-hook 'org-cdlatex-mode)
   #+end_src
   这样在 org-mode 中输入的时候就可以使用 cdlatex 对于 LaTeX 的补全了。对于这些，如果你会一些 LaTeX，这些还是很简单的，一通百通莫如是也。
   #+begin_src emacs-lisp
;; 由于我使用的 emacs 中的 ein 作为 jupyter notebook
;; 所以可以绑定 cdlatex 到 ein 使输入数学符号更加方便
(add-hook 'ein-mode-hook 'cdlatex-mode)
;; 这个没有用
   #+end_src
*** LaTeX with matplotlib
	如果想要使用 =XeLaTeX 或者 LuaLaTeX= 渲染图片，这里有三种方式
	- =matplotlib.use("pdf")=
	- ~plt.savefig("result.pdf", backend='pgf')~
	-
	#+begin_src python
from matplotlib.backends.backend_pgf import FigureCanvasPgf
matplotlib.backend_bases.register_backend('pdf', FigureCanvasPgf)
	#+end_src
	最主要的是你可以像写 LaTeX 一样，写入导言区，
	#+begin_src python :results file
import matplotlib as mpl
mpl.use("pgf")
import matplotlib.pyplot as plt
plt.rcParams.update({
    "font.family": "regular",
    "text.usetex": True,
    "pgf.preamble": "\n".join([
        r"\usepackage{url}",
        r"\usepackage{unicode-math}",
        r"\setmainfont{Sarasa Mono SC}"
    ])
})
fig, ax = plt.subplots(figsize=(4.5, 2.5))

ax.plot(range(5))

ax.set_xlabel("unicode text: я, ψ, €, ü")
ax.set_ylabel(r"\url{https://matplotlib.org}")
ax.legend(["unicode math: $λ=∑_i^∞ μ_i^2$"])

fig.tight_layout(pad=.5)
plt.savefig("pgf.pdf")
return "pgf.pdf"
	#+end_src

	#+RESULTS:
	[[file:pgf.pdf]]
	同样可以制定 编译器
	- ~XeLaTeX~
	- ~PdfLaTeX~
	- ~LuaLaTeX~
	  #+begin_src python :results file
import matplotlib as mpl
mpl.use("pgf")
import matplotlib.pyplot as plt
plt.rcParams.update({
    "font.family": "serif",
    "text.usetex": True,
    "pgf.texsystem": "xelatex",  # default is xelatex
    "pgf.preamble": "\n".join([
        r"\usepackage{url}",
        r"\usepackage{unicode-math}",
        r"\setmainfont{DejaVu Serif}"
    ])
})
# plt.rcParams['font.family']=['Sarasa Mono SC']
fig, ax = plt.subplots(figsize=(4.5, 2.5))

ax.plot(range(5))

ax.set_xlabel("哈哈哈哈unicode text: я, ψ, €, ü")
ax.set_ylabel(r"\url{https://matplotlib.org}")
ax.legend(["unicode math: $λ=∑_i^∞ μ_i^2$"])

fig.tight_layout(pad=.5)
plt.savefig("pgf2.pdf")
return "pgf2.pdf"
	  #+end_src

	  #+RESULTS:
	  [[file:]]
	  使用 LaTeX 来渲染文本 ~plt.rcParams["text.usetex"]=True~ ， *值得注意的是，当使用 LaTeX 渲染文本的时候，则需要注意 LaTeX 的特殊字符了* 。
	  #+begin_src python :results file
import numpy as np
import matplotlib.pyplot as plt
plt.rcParams['text.usetex'] = True

t = np.linspace(0.0, 1.0, 100)
s = np.cos(4 * np.pi * t) + 2

fig, ax = plt.subplots(figsize=(6, 4), tight_layout=True)
ax.plot(t, s)

ax.set_xlabel(r'\textbf{time (s)}')
ax.set_ylabel('\\textit{Velocity (\N{DEGREE SIGN}/sec)}', fontsize=16)
ax.set_title(r'\TeX\ is Number $\displaystyle\sum_{n=1}^\infty'
             r'\frac{-e^{i\pi}}{2^n}$!', fontsize=16, color='r')
plt.savefig("pgf3.pdf")
return "pgf3.pdf"
	  #+end_src

	  #+RESULTS:
	  [[file:]]
	  #+begin_src python :results file
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import host_subplot
import numpy as np

ax = host_subplot(111)
xx = np.arange(0, 2*np.pi, 0.01)
ax.plot(xx, np.sin(xx))

ax2 = ax.twin()  # ax2 is responsible for "top" axis and "right" axis
ax2.set_xticks([0., .5*np.pi, np.pi, 1.5*np.pi, 2*np.pi],
               labels=["$0$", r"$\frac{1}{2}\pi$",
                       r"$\pi$", r"$\frac{3}{2}\pi$", r"$2\pi$"])

ax2.axis["right"].major_ticklabels.set_visible(False)
ax2.axis["top"].major_ticklabels.set_visible(True)
plt.savefig("pgf4.pdf")
return "pgf4.pdf"
	  #+end_src

	  #+RESULTS:
	  [[file:]]
*** Customizing Figure Layouts Using GridSpec and Other Functions [2021-11-27 Sat 10:45]
今天学习一下定制面向对象方式画图的定制。首先会是 ~grid~ 排列，这个在每个画图语言里面都是非常常见的。用 =python= 来操作还是比较的简单。
*绘制多子图的时候，使用命令 ~plt.subplots_adjust(hspace=0.4, wspace=0.4)~ 来调整子图之间的距离* ，同时，在 =gridspec= 中能够直接使用
=hspace and wspace= 来调整的，但是在 ~plt.subplots()~ 没有这个参数，所以不能够直接使用。
**** 第一种
#+begin_src python :results file
import matplotlib.pyplot as plt
import numpy as np
fig1, f1_axes = plt.subplots(ncols=2, nrows=2, constrained_layout=True)
X = np.linspace(-2, 3, 30)
Y = np.sin(X) / X
# 由于创建的多维度数组，返回的多维度 numpy 数组，所以你要自己去识别
f1_axes[0][0].plot(X, Y)
f1_axes[1][1].plot(X, Y * X)
plt.savefig("one.pdf")
return "one.pdf"
#+end_src

#+RESULTS:
[[file:]]
下面搞个单维度
#+begin_src python :results file
import matplotlib.pyplot as plt
import numpy as np
fig1, f1_axes = plt.subplots(ncols=2, nrows=1, constrained_layout=True)
X = np.linspace(-2, 3, 30)
Y = np.sin(X) / X
# 由于创建的多维度数组，返回的多维度 numpy 数组，所以你要自己去识别
f1_axes[0].plot(X, Y)
f1_axes[1].plot(X, Y * X)
plt.savefig("two.pdf")
return "two.pdf"
#+end_src

#+RESULTS:
[[file:two.pdf]]
通过上面两个例子，可以知道，如果指定了多行和多列，那么则是多维度 numpy 数组，要按照多维度的数组去指定。
**** 第二种
使用 ~gridspec~ ，这种方式厉害的是可以实现跨行或者跨列的图。不过前提是多导入一个 ~import matplotlib.gridspec as gridspec~
#+begin_src python :results file
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
fig = plt.figure(constrained_layout=True)
spec = gridspec.GridSpec(ncols=2, nrows=2, hspace=0.5, wspace=0.5, figure=fig)
print(type(spec))
fig_ax1 = fig.add_subplot(spec[0, 0])
fig_ax2 = fig.add_subplot(spec[0, 1])
fig_ax3 = fig.add_subplot(spec[1, 0])
fig_ax4 = fig.add_subplot(spec[1, 1])
plt.savefig("three.pdf")
return "three.pdf"
#+end_src

#+RESULTS:
[[file:three.pdf]]
值得注意的是，使用的 numpy 数组的内容的获取，我估摸着是内部是 numpy 数组。\\
更厉害的， ~gridspec~ 可以有个更简便的方式，还可以合成跨行或者跨列的图片。（用这种方式，还不要导入 ~import matplotlib.gridspec as gridspec~ ）
#+begin_src python :results file
import matplotlib.pyplot as plt
fig = plt.figure(constrained_layout=True)
# fig.subplots_adjust(hspace=0.8,  wspace=0.4)
spec = fig.add_gridspec(3, 3)
fig_ax1 = fig.add_subplot(spec[0, :2])
fig_ax1.set_title("spec[0, :2]")
fig_ax2 = fig.add_subplot(spec[:2, 2])
fig_ax2.set_title("spec[:2, 2]")
fig_ax3 = fig.add_subplot(spec[1: , :2])
fig_ax3.set_title("spec[1:, :2]")
fig_ax4 = fig.add_subplot(spec[-1, -1])
fig_ax4.set_title("spec[-1, -1]")
plt.savefig("four.pdf")
return "four.pdf"
#+end_src

#+RESULTS:
[[file:four.pdf]]
但是我从书上也看见一种
#+begin_src python :results file
import matplotlib.pyplot as plt
fig = plt.figure(constrained_layout=True)
spec =plt.GridSpec(ncols=2, nrows=2, figure=fig)
print(type(spec))
fig_ax1 = fig.add_subplot(spec[0, 0])
fig_ax2 = fig.add_subplot(spec[0, 1])
fig_ax3 = fig.add_subplot(spec[1, 0])
fig_ax4 = fig.add_subplot(spec[1, 1])
plt.savefig("five.pdf")
return "five.pdf"
#+end_src

#+RESULTS:
[[file:five.pdf]]
基本的子图的划分就是这样了，当需要更加复杂的案例的时候，可以查阅 [[https://matplotlib.org/stable/tutorials/intermediate/gridspec.html][matplotlib.org]] 来了解，案例十分充足。
*** Constrained Layout Guide [2021-11-27 Sat 12:18]
两种方式使用这个布局
- ~fig=plt.figure(constrained_layout=True)~
- ~plt.rcParams["figure.constrained_layout.use"]=True~

  下面给出一个例子。
  #+begin_src python :results file
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import matplotlib.gridspec as gridspec
import numpy as np
import time


plt.rcParams['savefig.facecolor'] = "0.5"
plt.rcParams['figure.figsize'] = 4.5, 4.
plt.rcParams['figure.max_open_warning'] = 50


def example_plot(ax, fontsize=12, hide_labels=False):
    ax.plot([1, 2])

    ax.locator_params(nbins=3)
    if hide_labels:
        ax.set_xticklabels([])
        ax.set_yticklabels([])
        plt.save("six.pdf")
    else:
        ax.set_xlabel('x-label', fontsize=fontsize)
        ax.set_ylabel('y-label', fontsize=fontsize)
        ax.set_title('Title', fontsize=fontsize)

fig, ax = plt.subplots(constrained_layout=True)
example_plot(ax, fontsize=24)
plt.savefig("six.pdf")
return "six.pdf"
  #+end_src

  #+RESULTS:
  [[file:six.pdf]]
  总的来说吧，就是 ~constrained_layout=True~ 可以防止出现 label 显示不全，当有多子图的时候，可以是自动调整间距。
  好了，今天的 ~matplotlib~ 就到此为止了。
*** Text in Matplotlib Plots [2021-11-28 Sun 11:22]
今天学习一下在图像中添加文字，使用 ~plt.text()~ 等命令。面对对象画图的 API
| 面向对象的 API | 描述                       |
|----------------+----------------------------|
| text           | 在 Axes 的任意位置添加文本 |
| annotate       | 在 Axes 的任意位置添加文本 |
| set_xlabel     | 添加 X 轴的标签            |
| set_ylabel     | 添加 Y 轴的标签            |
| set_title      | 为 Axes 添加标题           |
| suptitle       | 为 Figure 添加标题         |
#+begin_src python :results file
import matplotlib.pyplot as plt
fig = plt.figure(constrained_layout=True)
ax = fig.add_subplot()
plt.suptitle("This is Figure title")
ax.set_title("This is axes title")
ax.set_xlabel("x label")
ax.set_ylabel("y label")
ax.axis([0, 10, 0, 10])
ax.text(3, 8, "A boxed in figure", bbox={"facecolor":"red", "alpha":0.5}, style="italic")
ax.text(2, 6, r"an Equation: E=mc^{2}")
ax.plot([2], [1], 'o')
ax.annotate('annotate', xy=(2, 1), xytext=(3, 4),
            arrowprops=dict(facecolor='black', shrink=0.05))
plt.savefig("seven.pdf")
return "seven.pdf"
#+end_src

#+RESULTS:
[[file:seven.pdf]]
如上案例主要是进行 text 的方法的应用，对 annotate 的应用下面一节进行学习。关于 text 的一些参数，可以从[[https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.text.html#matplotlib.axes.Axes.text][这里]]获得。
***
** Preview [2021-12-21 Tue 15:37]
由于接了一单 matplotlib 的作业，所以现在复习一下 matplotlib 中的一些基础的知识
*** 关于中文的问题和负号显示的问题
- 由于我是 Linux 系统，目前没有需要在图上显示中文的需求，这里只是记载关于 Windows 系统下的中文显示问题 ~plt.rcParams["font.sans-serif"] = ["Simhei"]~ 就可以解决问题
- 关于负号显示的问题，使用命令 ~plt.rcParams["axes.unicode_minus"] = False~ 就可以
*** 一些字符的含义
说是复习，其实这些东西比较常用但是我没有注意
| 字符 | Color | 字符 | Linestyle | 字符 | Marker   | 字符 | Marker   |
|------+-------+------+-----------+------+----------+------+----------|
| b    | 蓝色  | =-=  | 实线      | p    | 五角点   | v    | 倒三角   |
| g    | 绿色  | =-.= | 虚线      | h    | 六边形点 | <    | 左三角   |
| r    | 红色  | =--= | 虚线      | +    | 加号点   | l    | vline    |
| c    | 青色  | =:=  | 点线      | D    | 钻石     | =-=  | hline    |
| m    | 品红  |      |           | d    | 瘦菱形点 | ^    | 上三角点 |
| y    | 黄色  |      |           | *    | 星型点   | >    | 右三角点 |
| k    | 黑色  |      |           | s    | 正方点   | =.=  | 点       |
| w    | 白色  |      |           | x    | 乘号点   | o    | 原点       |
1. 控制 =Linestyle= ，使用参数 =ls=
   1. ~ls=":"~
2. 线条宽度，使用参数 =lw=
   1. ~lw=3~
3.
#+begin_src python :results file
import matplotlib.pyplot as plt
import numpy as np
plt.figure(figsize=(7, 6))
x = np.linspace(0, 10, 30)
y = np.sin(x)
plt.xlabel('axis-x', fontsize=15)
plt.ylabel('axis-y', fontsize=15)
a = plt.plot(x, y,
        color='c',
        marker='o',
        ls=":",
        lw=1)
plt.axis([-1, 11, -1.2, 1.2])
plt.xticks([0, np.pi, 2 * np.pi, 3 * np.pi],
          ["0", r"$\pi$", r"2$\pi$", r"$\pi$"],
          rotation=45)
plt.yticks(np.linspace(-1.2, 1.2, 9),
          [f"${r:.3}$" for r in np.linspace(-1.2, 1.2, 9)],
          rotation=90)
plt.title("I'm a title",
         bbox={
             "boxstyle": "square",
             "fc": 'c',         # 背景颜色
             "ec": "r",         # 边框颜色
             "alpha": 0.5
         },
          fontsize=12,
          fontweight="bold",
          rotation=30,
          color="blue",
          va="center",
          ha="center"
         )
for i, j in zip(x, y):
    if j > 0 :
        plt.text(i-0.2, j+0.1, f"{j:.2}", color='c', fontsize=10, rotation=45)
    else:
        plt.text(i-0.1, j-0.1, f"{j:.2}", color='c', fontsize=10, rotation=45)
# 添加网格线
plt.grid(ls=":", lw=2, color="y")
plt.savefig("p2.pdf")
return "p2.pdf"
#+end_src

#+RESULTS:
[[file:p2.pdf]]
*** 画气泡图(本质上就是不同大小的散点图)
气泡图就是把 ~marker~ 设置为 ~marker="o"~ ，并且把控制大小的参数 =s= 设置为随机数字
#+begin_src python :results file
import matplotlib.pyplot as plt
import numpy as np
n = 50
x1 = np.random.randn(n) * 5
y1 = np.random.randn(n) * 5
x2 = np.random.randn(n) * 5
y2 = np.random.randn(n) * 5
plt.figure(figsize=(7, 7))
plt.scatter(x1, y1,
           c = np.random.randn(n),
           cmap = "Blues",
           marker = "o",
           lw = 2,
           s = np.random.randint(0, 100, n),
           label="test1")
plt.grid(ls="-.", color="c")
plt.legend()
plt.savefig("p3.pdf")
return "p3.pdf"
#+end_src

#+RESULTS:
[[file:p3.pdf]]
*** 文本框注释(本质就是 text 函数使用 box 来装饰)
~plt.text(x, y, "I'm a text", bbox=dict({boxstyle="square", fc='y', ec='c'}))~
*** 水平线、垂直线以及色带
#+begin_src python :results file
import matplotlib.pyplot as plt
import numpy as np
plt.figure(figsize=(5, 5), dpi=100)
x = np.linspace(0, 3 * np.pi, 100)
y = np.sin(x)
plt.plot(x, y)
# 水平线
plt.axhline(y=0.4, xmin=0.1, xmax=np.pi, c="r", lw=3)
# 垂直线
plt.axvline(x=np.pi, ls=":", lw=2, color="c")
# 水平色带
plt.axhspan(ymin=-0.2, ymax=0.3, fc="m", alpha=0.3)
# 垂直色带
plt.axvspan(xmin=0.2, xmax=3, fc="lightblue", alpha=0.9)
plt.savefig("p4.pdf")
return "p4.pdf"
#+end_src

#+RESULTS:
[[file:p4.pdf]]

*** 箭头注释
不常用，需要查看官网进行解决

*** 移动坐标轴位置
~plt.gca()~ 返回当前的坐标轴

*** 柱状图
柱状图的填充物 ~hatch: {'/', '\\', '|', '-', '+', 'x', 'o', 'O', '.', '*'}~
#+begin_src python :results file
import matplotlib.pyplot as plt
import numpy as np
x = range(1, 5)
y = [1.5, 0.6, 7.8, 6]
err = [0.3, 0.1, 1.5, 1]
names = ["Monday", "Tuesday", "Friday", "Sunday"]

plt.figure(figsize=(5, 5))
plt.bar(x, y, width=0.4,
        color=["c", "r", "y", "b"],
        tick_label=names,       # 设置标签
        hatch="-",
        yerr=err                # 添加误差线
        )
plt.savefig("p5.pdf")
return "p5.pdf"
#+end_src

#+RESULTS:
[[file:p5.pdf]]
这里搞一个堆叠的柱状图
#+begin_src python :results file
import matplotlib.pyplot as plt
import numpy as np
x = range(1, 5)
y = [1.5, 0.6, 7.8, 6]
y2 = [1, 2, 3, 5]
names = ["Monday", "Tuesday", "Friday", "Sunday"]

plt.figure(figsize=(5, 5))
plt.bar(x, y, width=0.4,
        tick_label=names,       # 设置标签
        hatch="-",
        label="bottom")
plt.bar(x, y2, width=0.4,
        bottom=y,
        label="top")
plt.legend(frameon=True)
plt.savefig("p5.pdf")
return "p5.pdf"
#+end_src

#+RESULTS:
[[file:p5.pdf]]
这里搞一个并列的柱状图， *如果想要标签居中的话，使用 ~plt.xticks()~ 命令来进行调整 *
#+begin_src python :results file
import matplotlib.pyplot as plt
import numpy as np
x = range(1, 5)
y = [1.5, 0.6, 7.8, 6]
y2 = [1, 2, 3, 5]
width=0.4
names = ["Monday", "Tuesday", "Friday", "Sunday"]

plt.figure(figsize=(5, 5))
plt.bar(x, y, width=width,      # 设置标签
        hatch="-",
        label="bottom")

plt.bar(np.array(x)+width, y2, width=width,
        label="top")
plt.xticks(np.array(x)+width/2, names)
plt.legend(frameon=True)
plt.savefig("p5.pdf")
return "p5.pdf"
#+end_src

#+RESULTS:
[[file:p5.pdf]]

*** 条形图
本质上和柱状图没有啥区别
#+begin_src python :results file
import matplotlib.pyplot as plt
import numpy as np
x = range(1, 5)
y = [1.5, 0.6, 7.8, 6]
err = [0.3, 0.1, 1.5, 1]
names = ["Monday", "Tuesday", "Friday", "Sunday"]

plt.figure(figsize=(5, 5))
plt.barh(x, y,
        color=["c", "r", "y", "b"],
        tick_label=names,       # 设置标签
        hatch="-",
        xerr=err                # 添加误差线
        )
plt.savefig("p5.pdf")
return "p5.pdf"
#+end_src

#+RESULTS:
[[file:p5.pdf]]

*** 填充图线
#+begin_src python :results file
import matplotlib.pyplot as plt
import numpy as np
plt.figure(figsize=(4, 4))
x = np.linspace(0, 5 * np.pi, 100)
y = np.sin(x)
plt.plot(x, y)
plt.fill(x, y, fc="y")
plt.savefig("tc.pdf")
return "tc.pdf"
#+end_src

#+RESULTS:
[[file:tc.pdf]]

*** 饼图
#+begin_src python :results file
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np
labels = ["A", "B", "C", "D"]
students = [0.34, 0.15, 0.21, 0.3]
colors = ["c", "r", "b", "y"]
explode = [0, 0.24, 0.36, 0]
plt.figure(figsize=(7, 7))
plt.pie(students, labels=labels,
        colors=cm.ScalarMappable().to_rgba(students),
        autopct="%3.0f%%",      # 饼图内的数据标签
        pctdistance=0.45,       # 数据标签里圆心的距离
        startangle=90,          # 第一块的位置
        radius=1.2,             # 半径
        shadow=True,            # 阴影有
        explode=explode,         # 块分布加强
        )
sm = plt.cm.ScalarMappable(norm = plt.Normalize(vmin=0.08, vmax=0.3))
plt.colorbar(sm)
plt.savefig("bt.pdf")
return "bt.pdf"
#+end_src

#+RESULTS:
[[file:bt.pdf]]

*** 阶梯图
#+begin_src python :results file
import matplotlib.pyplot as plt
import numpy as np
plt.figure(figsize=(5, 5))
x = np.linspace(0, 2 * np.pi, 100)
y = np.sin(x)
plt.plot(x, y, color="r")
plt.step(x, y,
         color="c",
         lw=1,
         where="post"            # 阶梯在数据点之前，之后为 post
         )
plt.savefig("jt.pdf")
return "jt.pdf"
#+end_src

#+RESULTS:
[[file:jt.pdf]]

*** 直方图
#+begin_src python :results file
import matplotlib.pyplot as plt
import numpy as np
mu, sigma = 100, 15
datas = mu + sigma * np.random.randn(10000)
plt.figure(figsize=(8, 7))
# 直方图的形式
histstyles = ["bar", "step", "stepfilled", "barstacked"]

for i in range(len(histstyles)):
    plt.subplot(221 + i)
    plt.hist(datas,
             bins=15,            # 直方图中柱子的数量
             lw=2,
             ec="purple",
             histtype=histstyles[i]
             )
    plt.title(f"histstyle={histstyles[i]}")

plt.savefig("zf.pdf")
return "zf.pdf"
#+end_src

#+RESULTS:
[[file:zf.pdf]]

*** 绵棒图
*** 极坐标气泡图
#+begin_src python :results file
import matplotlib.pyplot as plt
import numpy as np
N = 100
r = 5 * np.random.rand(N)
theta = 2 * np.pi * np.random.rand(N)
area = 200 * r * 2
colors = theta
plt.figure(figsize=(4, 4))
ax = plt.subplot(111, projection="polar")
ax.scatter(theta, r, alpha=0.4, c=colors, cmap="hsv",s=area, marker="o")
plt.savefig("jz.pdf")
return "jz.pdf"
#+end_src

#+RESULTS:
[[file:jz.pdf]]
