#+TITLE: About the Server
#+DATE:[2021-11-24 Wed 14:52]
* Preface
  我一直对于服务器这方面的只是不是很了解，这篇博客慢慢的来了解
* 概念
  服务器是就是我们计算机的一种，性能更加的强大，基本内部结构和我们普通的计算机没有什么基础差别，细节更加的多。（本地的电脑可以作为一个服务器，我同学自己搞博客网站实现了，
  但是肯定不足）
  服务器性能要求比较高，稳定性也是需要比较高。
* 作用
  服务器主要是用来响应终端的服务请求，我们上网就是通过服务器来链接网络，当服务器响应了我们的请求，就是上网成功的时候。（大部分的功能都是服务器完成的）
* 服务器分类
** 物理形态分类
*** 服务器
	放在远程机房的独立计算机。
*** ECS 服务器
	就是现在比较流行的云服务器(Elastic Compute Service)，通常都是自己选 *容量、CPU能力、内存* 所以也是被叫做弹性计算服务器。
*** VPS服务器
	虚拟专用服务器(Virtual Private Server)，即是将一台独立服务器通过虚拟技术分割为若干个虚拟服务器，每个 VPS 可以独立安装系统，拥有独立的 IP，内存，CPU 等是独立的使用的，
	VPS 可以像独立服务器一样重装系统和安装程序等
*** 虚拟主机
	将一台已安装操作系统和安全防范的服务器通过技术手段分割为若干个独立的空间，分配给用户独立使用，解析绑定域名就能够使用。 *虚拟主机无法安装系统和操作软件* ，只能运行网站脚本语言或者
	html 文件，图片以及其他的若干文件。（github.io 博客自定义域名就是这个玩意。）（虚拟主机就是多个用户租用了一台服务器）
** 物理位置分类
*** 国内主机
*** 国外主机
	- 国内主机必须备案，国外主机不需要提交备案资料
	- 国内主机国内快，国外主机一样的的道理
	- 线路：国内主机有线路限制，海外主机没有，国内的主机线路以联通和电信为主，相同的线路访问不存在速度限制，但相互访问会存在问题
* 服务器关键参数指标
  - 操作系统 :: Linux 首推。
  - 支持脚本 :: 根据自己需要网站程序所使用的开发语言选择，支持语言越少的越安全。
  - 空间容量 :: 存放文件的空间大小，一般来说 1-5 G。
  - 主机带宽 :: 主机支持的最大下行访问速度，直接影响网站的访问速度，同时也要考虑一台服务器有多少个网站。
  - 访问流量 :: 对我不太重要，有用及查。
  - 并发量 :: 同一时刻请求访问网站的用户数量。

（ *暂时到这* ）
